definitions:
  api.LoginInfo:
    properties:
      device_id:
        type: string
      login_token:
        type: string
      login_type:
        type: string
    required:
    - device_id
    - login_token
    - login_type
    type: object
  app.Response:
    properties:
      code:
        type: integer
      data: {}
      msg:
        type: string
    type: object
info:
  contact: {}
  description: An example of gin
  license:
    name: MIT
    url: https://github.com/coolishbee/go-gin-sample/blob/main/LICENSE
  termsOfService: https://github.com/coolishbee/go-gin-sample
  title: Golang Gin API
  version: "1.0"
paths:
  /api/autologin:
    get:
      parameters:
      - description: SessionID for login authentication
        in: query
        name: sessionkey
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: Get AutoLogin
  /api/login:
    post:
      parameters:
      - description: LoginInfo Body
        in: body
        name: auth
        required: true
        schema:
          $ref: '#/definitions/api.LoginInfo'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: Post Login
swagger: "2.0"
