definitions:
  api.socialAuth:
    properties:
      login_token:
        type: string
      login_type:
        type: string
    required:
    - login_token
    - login_type
    type: object
  app.Response:
    properties:
      code:
        type: integer
      data: {}
      msg:
        type: string
    type: object
info:
  contact: {}
  description: An example of gin
  license:
    name: MIT
    url: https://github.com/coolishbee/go-gin-sample/blob/main/LICENSE
  termsOfService: https://github.com/coolishbee/go-gin-sample
  title: Golang Gin API
  version: "1.0"
paths:
  /auth:
    post:
      parameters:
      - description: socialAuth Body
        in: body
        name: auth
        required: true
        schema:
          $ref: '#/definitions/api.socialAuth'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: Post Auth
swagger: "2.0"
